services:
  - type: web
    name: quran-search
    env: python
    plan: free
    buildCommand: pip install -r quran/requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT --chdir quran app:app
    healthCheckPath: /api/health
